In [2]:
import pandas as pd

In [4]:
df = pd.DataFrame([[1,9,7,4],[5,6,8,7],[7,5,4,3]])
df

   0  1  2  3
0  1  9  7  4
1  5  6  8  7
2  7  5  4  3

In [6]:
df1=pd.DataFrame({"name":["sam","ram","tom"],"class":["btech","mca","bca"],"rollno":[34,56,89]})
df1

  name  class  rollno
0  sam  btech      34
1  ram    mca      56
2  tom    bca      89

##### Functions

In [11]:
df.head(6) # agar 6 nhi hai tabh bhi print kr dega.

   0  1  2  3
0  1  9  7  4
1  5  6  8  7
2  7  5  4  3

In [10]:
df.tail() # by default last 5 values

   0  1  2  3
0  1  9  7  4
1  5  6  8  7
2  7  5  4  3