In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame([[1,9,7,4],[5,6,8,7],[7,5,4,3]])
df

   0  1  2  3
0  1  9  7  4
1  5  6  8  7
2  7  5  4  3

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       3 non-null      int64
 1   1       3 non-null      int64
 2   2       3 non-null      int64
 3   3       3 non-null      int64
dtypes: int64(4)
memory usage: 228.0 bytes

In [5]:
df.columns

RangeIndex(start=0, stop=4, step=1)

In [6]:
# iterrows isme we use forloop

In [7]:
df1=pd.DataFrame({'a':[1,2,3,4],'b':[4,3,2,1],'c':[3,7,80,5]})
df1

   a  b   c
0  1  4   3
1  2  3   7
2  3  2  80
3  4  1   5

In [8]:
df2=pd.DataFrame({'a':[11,2,3,4],'b':[4,3,24,1],'c':[3,7,8,5]})
df2

    a   b  c
0  11   4  3
1   2   3  7
2   3  24  8
3   4   1  5

In [ ]:
# ignore index joh hai voh index ko 0to 9 tak likhega otherwise 0to4 again 0to4.
#Axis joh hai voh column wise concate krega. if axis =1 then col, axis =0 then row .